// Generated by tools/gen_strings.py from shared/i18n/languages.json. Do not edit.
package sa.zood.nearmosque.core

/** An interface language: the app's own [code] (content packs, Ask), its name in itself, and its locale [tag]. */
data class Language(val code: String, val name: String, val rtl: Boolean, val tag: String)

object Languages {
    val all: List<Language> = listOf(
        Language("en", "English", false, "en"),
        Language("ar", "العربية", true, "ar"),
        Language("ur", "اردو", true, "ur"),
        Language("tr", "Türkçe", false, "tr"),
        Language("id", "Bahasa Indonesia", false, "id"),
        Language("fr", "Français", false, "fr"),
        Language("es", "Español", false, "es"),
        Language("ru", "Русский", false, "ru"),
        Language("bn", "বাংলা", false, "bn"),
        Language("fa", "فارسی", true, "fa"),
        Language("prs", "دری", true, "fa-AF"),
        Language("zh", "中文（简体）", false, "zh-Hans"),
        Language("hi", "हिन्दी", false, "hi"),
        Language("pt", "Português", false, "pt"),
        Language("ha", "Hausa", false, "ha"),
        Language("sw", "Kiswahili", false, "sw"),
        Language("tl", "Tagalog", false, "fil"),
        Language("vi", "Tiếng Việt", false, "vi"),
        Language("th", "ไทย", false, "th"),
        Language("km", "ខ្មែរ", false, "km"),
        Language("ug", "ئۇيغۇرچە", true, "ug"),
        Language("ckb", "کوردی", true, "ckb"),
        Language("bs", "Bosanski", false, "bs"),
        Language("sr", "Српски", false, "sr"),
        Language("mk", "Македонски", false, "mk"),
        Language("hu", "Magyar", false, "hu"),
        Language("nl", "Nederlands", false, "nl"),
        Language("ka", "ქართული", false, "ka"),
        Language("si", "සිංහල", false, "si"),
        Language("te", "తెలుగు", false, "te"),
        Language("kn", "ಕನ್ನಡ", false, "kn"),
        Language("ml", "മലയാളം", false, "ml"),
        Language("mr", "मराठी", false, "mr"),
        Language("gu", "ગુજરાતી", false, "gu"),
        Language("pa", "ਪੰਜਾਬੀ", false, "pa"),
        Language("as", "অসমীয়া", false, "as"),
    )
    private val byCode = all.associateBy { it.code }

    fun isRtl(code: String): Boolean = byCode[code]?.rtl ?: false
    fun tag(code: String): String = byCode[code]?.tag ?: code
    fun name(code: String): String = byCode[code]?.name ?: code

    /** The app's code for a platform locale: its language, with the region or script where they pick a variant. */
    fun code(language: String, region: String = "", script: String = ""): String {
        val lang = when (language) { "in" -> "id"; "iw" -> "he"; "tl" -> "fil"; else -> language }
        val parts = all.map { it to it.tag.split("-") }.filter { it.second[0] == lang }
        val exact = parts.firstOrNull { (_, p) -> p.size > 1 && (p[1] == region || p[1] == script) }
        val plain = parts.firstOrNull { (_, p) -> p.size == 1 || (p[1].length == 4 && script.isEmpty()) }
        return (exact ?: plain ?: parts.firstOrNull())?.first?.code ?: lang
    }
}
