// Generated by tools/gen_strings.py from shared/i18n/languages.json. Do not edit.
import Foundation

/// Interface languages: the app's own code (content packs, Ask), the name in itself, right-to-left, the
/// locale tag and the .lproj folder.
public enum Languages {
    public struct Language: Sendable, Hashable {
        public let code: String
        public let name: String
        public let rtl: Bool
        public let tag: String
        public let lproj: String
    }

    public static let all: [Language] = [
        Language(code: "en", name: "English", rtl: false, tag: "en", lproj: "en"),
        Language(code: "ar", name: "العربية", rtl: true, tag: "ar", lproj: "ar"),
        Language(code: "ur", name: "اردو", rtl: true, tag: "ur", lproj: "ur"),
        Language(code: "tr", name: "Türkçe", rtl: false, tag: "tr", lproj: "tr"),
        Language(code: "id", name: "Bahasa Indonesia", rtl: false, tag: "id", lproj: "id"),
        Language(code: "fr", name: "Français", rtl: false, tag: "fr", lproj: "fr"),
        Language(code: "es", name: "Español", rtl: false, tag: "es", lproj: "es"),
        Language(code: "ru", name: "Русский", rtl: false, tag: "ru", lproj: "ru"),
        Language(code: "bn", name: "বাংলা", rtl: false, tag: "bn", lproj: "bn"),
        Language(code: "fa", name: "فارسی", rtl: true, tag: "fa", lproj: "fa"),
        Language(code: "prs", name: "دری", rtl: true, tag: "fa-AF", lproj: "fa-AF"),
        Language(code: "zh", name: "中文（简体）", rtl: false, tag: "zh-Hans", lproj: "zh-Hans"),
        Language(code: "hi", name: "हिन्दी", rtl: false, tag: "hi", lproj: "hi"),
        Language(code: "pt", name: "Português", rtl: false, tag: "pt", lproj: "pt"),
        Language(code: "ha", name: "Hausa", rtl: false, tag: "ha", lproj: "ha"),
        Language(code: "sw", name: "Kiswahili", rtl: false, tag: "sw", lproj: "sw"),
        Language(code: "tl", name: "Tagalog", rtl: false, tag: "fil", lproj: "fil"),
        Language(code: "vi", name: "Tiếng Việt", rtl: false, tag: "vi", lproj: "vi"),
        Language(code: "th", name: "ไทย", rtl: false, tag: "th", lproj: "th"),
        Language(code: "km", name: "ខ្មែរ", rtl: false, tag: "km", lproj: "km"),
        Language(code: "ug", name: "ئۇيغۇرچە", rtl: true, tag: "ug", lproj: "ug"),
        Language(code: "ckb", name: "کوردی", rtl: true, tag: "ckb", lproj: "ckb"),
        Language(code: "bs", name: "Bosanski", rtl: false, tag: "bs", lproj: "bs"),
        Language(code: "sr", name: "Српски", rtl: false, tag: "sr", lproj: "sr"),
        Language(code: "mk", name: "Македонски", rtl: false, tag: "mk", lproj: "mk"),
        Language(code: "hu", name: "Magyar", rtl: false, tag: "hu", lproj: "hu"),
        Language(code: "nl", name: "Nederlands", rtl: false, tag: "nl", lproj: "nl"),
        Language(code: "ka", name: "ქართული", rtl: false, tag: "ka", lproj: "ka"),
        Language(code: "si", name: "සිංහල", rtl: false, tag: "si", lproj: "si"),
        Language(code: "te", name: "తెలుగు", rtl: false, tag: "te", lproj: "te"),
        Language(code: "kn", name: "ಕನ್ನಡ", rtl: false, tag: "kn", lproj: "kn"),
        Language(code: "ml", name: "മലയാളം", rtl: false, tag: "ml", lproj: "ml"),
        Language(code: "mr", name: "मराठी", rtl: false, tag: "mr", lproj: "mr"),
        Language(code: "gu", name: "ગુજરાતી", rtl: false, tag: "gu", lproj: "gu"),
        Language(code: "pa", name: "ਪੰਜਾਬੀ", rtl: false, tag: "pa", lproj: "pa"),
        Language(code: "as", name: "অসমীয়া", rtl: false, tag: "as", lproj: "as"),
    ]
    private static let byCode = Dictionary(uniqueKeysWithValues: all.map { ($0.code, $0) })

    public static func isRTL(_ code: String) -> Bool { byCode[code]?.rtl ?? false }
    public static func tag(_ code: String) -> String { byCode[code]?.tag ?? code }
    public static func lproj(_ code: String) -> String { byCode[code]?.lproj ?? code }
    public static func name(_ code: String) -> String { byCode[code]?.name ?? code }

    /// The app's code for a locale identifier ("fa-AF", "zh-Hans-CN", "fil", "in"), or nil when not offered.
    public static func code(identifier: String) -> String? {
        let p = identifier.replacingOccurrences(of: "_", with: "-").split(separator: "-").map(String.init)
        guard var lang = p.first else { return nil }
        if lang == "in" { lang = "id" }
        if lang == "tl" { lang = "fil" }
        let rest = Set(p.dropFirst())
        let same = all.filter { $0.tag.split(separator: "-").first.map(String.init) == lang }
        if let exact = same.first(where: { l in l.tag.split(separator: "-").dropFirst().contains { rest.contains(String($0)) } }) { return exact.code }
        let plain = same.first { l in
            let tail = l.tag.split(separator: "-").dropFirst()
            return tail.isEmpty || (tail.first?.count == 4 && !rest.contains { $0.count == 4 })
        }
        return (plain ?? same.first)?.code
    }
}
