// Generated by tools/gen_strings.py from shared/i18n/languages.json. Do not edit.
import Foundation

/// Interface languages: the app's own code (content packs, Ask), the name in itself, right-to-left, the
/// locale tag and the .lproj folder.
public enum Languages {
    public struct Language: Sendable, Hashable {
        public let code: String
        public let name: String
        public let rtl: Bool
        public let tag: String
        public let lproj: String
    }

    public static let all: [Language] = [
        Language(code: "en", name: "English", rtl: false, tag: "en", lproj: "en"),
        Language(code: "ar", name: "العربية", rtl: true, tag: "ar", lproj: "ar"),
        Language(code: "ur", name: "اردو", rtl: true, tag: "ur", lproj: "ur"),
        Language(code: "tr", name: "Türkçe", rtl: false, tag: "tr", lproj: "tr"),
        Language(code: "id", name: "Bahasa Indonesia", rtl: false, tag: "id", lproj: "id"),
        Language(code: "fr", name: "Français", rtl: false, tag: "fr", lproj: "fr"),
        Language(code: "es", name: "Español", rtl: false, tag: "es", lproj: "es"),
    ]
    private static let byCode = Dictionary(uniqueKeysWithValues: all.map { ($0.code, $0) })

    public static func isRTL(_ code: String) -> Bool { byCode[code]?.rtl ?? false }
    public static func tag(_ code: String) -> String { byCode[code]?.tag ?? code }
    public static func lproj(_ code: String) -> String { byCode[code]?.lproj ?? code }
    public static func name(_ code: String) -> String { byCode[code]?.name ?? code }

    /// The app's code for a locale identifier ("fa-AF", "zh-Hans-CN", "fil", "in"), or nil when not offered.
    public static func code(identifier: String) -> String? {
        let p = identifier.replacingOccurrences(of: "_", with: "-").split(separator: "-").map(String.init)
        guard var lang = p.first else { return nil }
        if lang == "in" { lang = "id" }
        if lang == "tl" { lang = "fil" }
        let rest = Set(p.dropFirst())
        let same = all.filter { $0.tag.split(separator: "-").first.map(String.init) == lang }
        if let exact = same.first(where: { l in l.tag.split(separator: "-").dropFirst().contains { rest.contains(String($0)) } }) { return exact.code }
        let plain = same.first { l in
            let tail = l.tag.split(separator: "-").dropFirst()
            return tail.isEmpty || (tail.first?.count == 4 && !rest.contains { $0.count == 4 })
        }
        return (plain ?? same.first)?.code
    }
}
