#!/usr/bin/env python3
"""Generate platform string resources from shared/i18n/strings.json.

  python3 gen_strings.py          # write iOS Localizable.xcstrings + Android values*/strings.xml
  python3 gen_strings.py --check  # fail if generated files are out of date or a translation is missing
"""
import json
import os
import re
import sys

ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..")
SRC = os.path.join(ROOT, "shared", "i18n", "strings.json")
IOS_OUT = os.path.join(ROOT, "ios", "App", "Resources", "Localizable.xcstrings")
ANDROID_RES = os.path.join(ROOT, "android", "app", "src", "main", "res")
ANDROID_DIR = {"en": "values", "ar": "values-ar", "ur": "values-ur", "tr": "values-tr",
               "id": "values-in", "fr": "values-fr", "es": "values-es"}
PLACEHOLDER = re.compile(r"%(\d+\$)?([-+ 0#]*\d*)([sd])")


def placeholders(s):
    return sorted((m.group(1) or "", m.group(3)) for m in PLACEHOLDER.finditer(s.replace("%%", "")))


def to_ios(s):
    return PLACEHOLDER.sub(lambda m: "%" + (m.group(1) or "") + m.group(2) + ("@" if m.group(3) == "s" else "lld"), s)


def android_escape(s):
    s = s.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
    s = s.replace("\\", "\\\\").replace("'", "\\'").replace('"', '\\"').replace("\n", "\\n")
    if s.startswith("@") or s.startswith("?"):
        s = "\\" + s
    return s


def validate(data):
    langs = data["languages"]
    errors = []
    for key, entry in data["strings"].items():
        if not re.fullmatch(r"[a-z][a-z0-9_A-Z]*", key):
            errors.append(f"bad key {key}")
        plural = entry.get("plural", False)
        for lang in langs:
            if lang not in entry:
                errors.append(f"{key}: missing {lang}")
                continue
            if plural:
                if "other" not in entry[lang]:
                    errors.append(f"{key}/{lang}: plural without 'other'")
            elif placeholders(entry[lang]) != placeholders(entry["en"]):
                errors.append(f"{key}/{lang}: placeholders {placeholders(entry[lang])} != en {placeholders(entry['en'])}")
    return errors


def build_ios(data):
    out = {"sourceLanguage": "en", "version": "1.0", "strings": {}}
    for key in sorted(data["strings"]):
        entry = data["strings"][key]
        locs = {}
        for lang in data["languages"]:
            if entry.get("plural"):
                locs[lang] = {"variations": {"plural": {
                    cat: {"stringUnit": {"state": "translated", "value": to_ios(v)}}
                    for cat, v in entry[lang].items()}}}
            else:
                locs[lang] = {"stringUnit": {"state": "translated", "value": to_ios(entry[lang])}}
        out["strings"][key] = {"extractionState": "manual", "localizations": locs}
    return json.dumps(out, ensure_ascii=False, indent=2, sort_keys=False) + "\n"


def build_android(data, lang):
    lines = ['<?xml version="1.0" encoding="utf-8"?>',
             "<!-- Generated by tools/gen_strings.py from shared/i18n/strings.json. Do not edit. -->",
             "<resources>"]
    for key in sorted(data["strings"]):
        entry = data["strings"][key]
        attrs = ' translatable="false"' if key == "app_name" and lang != "en" and False else ""
        if entry.get("plural"):
            lines.append(f'    <plurals name="{key}">')
            for cat, v in entry[lang].items():
                lines.append(f'        <item quantity="{cat}">{android_escape(v)}</item>')
            lines.append("    </plurals>")
        else:
            fmt = ' formatted="false"' if "%" in entry[lang] and not PLACEHOLDER.search(entry[lang]) else ""
            lines.append(f'    <string name="{key}"{attrs}{fmt}>{android_escape(entry[lang])}</string>')
    lines.append("</resources>")
    return "\n".join(lines) + "\n"


def build_ios_infoplist(data):
    """InfoPlist.xcstrings: localized display name and permission purpose strings."""
    keys = {"CFBundleDisplayName": "app_name", "NSLocationWhenInUseUsageDescription": "permission_location_ios"}
    out = {"sourceLanguage": "en", "version": "1.0", "strings": {}}
    for plist_key, src in keys.items():
        entry = data["strings"][src]
        out["strings"][plist_key] = {"extractionState": "manual", "localizations": {
            lang: {"stringUnit": {"state": "translated", "value": entry[lang]}} for lang in data["languages"]}}
    return json.dumps(out, ensure_ascii=False, indent=2) + "\n"


def main():
    check = "--check" in sys.argv
    data = json.load(open(SRC, encoding="utf-8"))
    errors = validate(data)
    if errors:
        print("\n".join(errors))
        sys.exit(1)
    outputs = {IOS_OUT: build_ios(data), IOS_OUT.replace("Localizable.xcstrings", "InfoPlist.xcstrings"): build_ios_infoplist(data)}
    for lang, d in ANDROID_DIR.items():
        outputs[os.path.join(ANDROID_RES, d, "strings.xml")] = build_android(data, lang)
    stale = []
    for path, content in outputs.items():
        if check:
            if not os.path.exists(path) or open(path, encoding="utf-8").read() != content:
                stale.append(path)
        else:
            os.makedirs(os.path.dirname(path), exist_ok=True)
            with open(path, "w", encoding="utf-8") as f:
                f.write(content)
    if stale:
        print("out of date:", *stale, sep="\n  ")
        sys.exit(1)
    print(f"{len(data['strings'])} keys x {len(data['languages'])} languages " + ("ok" if check else "written"))


if __name__ == "__main__":
    main()
