#!/usr/bin/env python3
"""Generate platform string resources from shared/i18n/strings.json and shared/i18n/languages.json.

  python3 gen_strings.py          # write iOS Localizable.xcstrings + Android values*/strings.xml
  python3 gen_strings.py --check  # fail if generated files are out of date or a translation is missing

languages.json lists every interface language; the enabled ones are shipped. From it this also writes
Android's locales_config.xml, the Languages tables of both cores (codes, names, right-to-left, platform
locale tags), the CFBundleLocalizations line of ios/project.yml and Android's localeFilters.
"""
import json
import os
import re
import sys

ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..")
SRC = os.path.join(ROOT, "shared", "i18n", "strings.json")
IOS_OUT = os.path.join(ROOT, "ios", "App", "Resources", "Localizable.xcstrings")
IOS_TV_INFOPLIST = os.path.join(ROOT, "ios", "TV", "Resources", "InfoPlist.xcstrings")
ANDROID_RES = os.path.join(ROOT, "android", "app", "src", "main", "res")
LANGS_SRC = os.path.join(ROOT, "shared", "i18n", "languages.json")
LANGUAGES = [l for l in json.load(open(LANGS_SRC, encoding="utf-8"))["languages"] if l["enabled"]]
ANDROID_DIR = {l["code"]: l["android"] for l in LANGUAGES}
IOS_CODE = {l["code"]: l["ios"] for l in LANGUAGES}
KOTLIN_OUT = os.path.join(ROOT, "android", "core", "src", "main", "kotlin", "sa", "zood", "nearmosque", "core", "Languages.kt")
SWIFT_OUT = os.path.join(ROOT, "ios", "Packages", "NearestMosqueKit", "Sources", "NMCore", "Languages.swift")
LOCALES_OUT = os.path.join(ROOT, "android", "app", "src", "main", "res", "xml", "locales_config.xml")
PROJECT_YML = os.path.join(ROOT, "ios", "project.yml")
GRADLE = os.path.join(ROOT, "android", "app", "build.gradle.kts")
PLACEHOLDER = re.compile(r"%(\d+\$)?([-+ 0#]*\d*)([sd])")


def placeholders(s):
    return sorted((m.group(1) or "", m.group(3)) for m in PLACEHOLDER.finditer(s.replace("%%", "")))


def to_ios(s):
    return PLACEHOLDER.sub(lambda m: "%" + (m.group(1) or "") + m.group(2) + ("@" if m.group(3) == "s" else "lld"), s)


def android_escape(s):
    s = s.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
    s = s.replace("\\", "\\\\").replace("'", "\\'").replace('"', '\\"').replace("\n", "\\n")
    if s.startswith("@") or s.startswith("?"):
        s = "\\" + s
    return s


def validate(data):
    langs = data["languages"]
    errors = []
    for key, entry in data["strings"].items():
        if not re.fullmatch(r"[a-z][a-z0-9_A-Z]*", key):
            errors.append(f"bad key {key}")
        plural = entry.get("plural", False)
        for lang in langs:
            if lang not in entry:
                errors.append(f"{key}: missing {lang}")
                continue
            if plural:
                if "other" not in entry[lang]:
                    errors.append(f"{key}/{lang}: plural without 'other'")
            elif placeholders(entry[lang]) != placeholders(entry["en"]):
                errors.append(f"{key}/{lang}: placeholders {placeholders(entry[lang])} != en {placeholders(entry['en'])}")
    return errors


def build_ios(data):
    out = {"sourceLanguage": "en", "version": "1.0", "strings": {}}
    for key in sorted(data["strings"]):
        entry = data["strings"][key]
        locs = {}
        for lang in data["languages"]:
            if entry.get("plural"):
                locs[IOS_CODE[lang]] = {"variations": {"plural": {
                    cat: {"stringUnit": {"state": "translated", "value": to_ios(v)}}
                    for cat, v in entry[lang].items()}}}
            else:
                locs[IOS_CODE[lang]] = {"stringUnit": {"state": "translated", "value": to_ios(entry[lang])}}
        out["strings"][key] = {"extractionState": "manual", "localizations": locs}
    return json.dumps(out, ensure_ascii=False, indent=2, sort_keys=False) + "\n"


def build_android(data, lang):
    lines = ['<?xml version="1.0" encoding="utf-8"?>',
             "<!-- Generated by tools/gen_strings.py from shared/i18n/strings.json. Do not edit. -->",
             "<resources>"]
    for key in sorted(data["strings"]):
        entry = data["strings"][key]
        attrs = ' translatable="false"' if key == "app_name" and lang != "en" and False else ""
        if entry.get("plural"):
            lines.append(f'    <plurals name="{key}">')
            for cat, v in entry[lang].items():
                lines.append(f'        <item quantity="{cat}">{android_escape(v)}</item>')
            lines.append("    </plurals>")
        else:
            fmt = ' formatted="false"' if "%" in entry[lang] and not PLACEHOLDER.search(entry[lang]) else ""
            lines.append(f'    <string name="{key}"{attrs}{fmt}>{android_escape(entry[lang])}</string>')
    lines.append("</resources>")
    return "\n".join(lines) + "\n"


def build_ios_infoplist(data, tv=False):
    """InfoPlist.xcstrings: localized display name and permission purpose strings (the Apple TV app's own)."""
    # NSLocationUsageDescription: the same purpose string for the Mac app (macOS reads this key).
    keys = {"CFBundleDisplayName": "app_name", "NSLocationWhenInUseUsageDescription": "permission_location_ios",
            "NSLocationUsageDescription": "permission_location_ios"}
    if tv:
        keys = {"CFBundleDisplayName": "app_name", "NSLocationWhenInUseUsageDescription": "permission_location_tv"}
    out = {"sourceLanguage": "en", "version": "1.0", "strings": {}}
    for plist_key, src in keys.items():
        entry = data["strings"][src]
        out["strings"][plist_key] = {"extractionState": "manual", "localizations": {
            IOS_CODE[lang]: {"stringUnit": {"state": "translated", "value": entry[lang]}} for lang in data["languages"]}}
    return json.dumps(out, ensure_ascii=False, indent=2) + "\n"


def build_locales_config():
    lines = ['<?xml version="1.0" encoding="utf-8"?>',
             "<!-- Generated by tools/gen_strings.py from shared/i18n/languages.json. Do not edit. -->",
             '<locale-config xmlns:android="http://schemas.android.com/apk/res/android">']
    lines += [f'    <locale android:name="{l["tag"]}" />' for l in LANGUAGES]
    return "\n".join(lines + ["</locale-config>"]) + "\n"


def kotlin_str(s):
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"').replace("$", "\\$") + '"'


def build_kotlin():
    rows = ",\n".join(f'        Language({kotlin_str(l["code"])}, {kotlin_str(l["name"])}, {str(l["rtl"]).lower()}, {kotlin_str(l["tag"])})'
                      for l in LANGUAGES)
    return f"""// Generated by tools/gen_strings.py from shared/i18n/languages.json. Do not edit.
package sa.zood.nearmosque.core

/** An interface language: the app's own [code] (content packs, Ask), its name in itself, and its locale [tag]. */
data class Language(val code: String, val name: String, val rtl: Boolean, val tag: String)

object Languages {{
    val all: List<Language> = listOf(
{rows},
    )
    private val byCode = all.associateBy {{ it.code }}

    fun isRtl(code: String): Boolean = byCode[code]?.rtl ?: false
    fun tag(code: String): String = byCode[code]?.tag ?: code
    fun name(code: String): String = byCode[code]?.name ?: code

    /** The app's code for a platform locale: its language, with the region or script where they pick a variant. */
    fun code(language: String, region: String = "", script: String = ""): String {{
        val lang = when (language) {{ "in" -> "id"; "iw" -> "he"; "tl" -> "fil"; else -> language }}
        val parts = all.map {{ it to it.tag.split("-") }}.filter {{ it.second[0] == lang }}
        val exact = parts.firstOrNull {{ (_, p) -> p.size > 1 && (p[1] == region || p[1] == script) }}
        val plain = parts.firstOrNull {{ (_, p) -> p.size == 1 || (p[1].length == 4 && script.isEmpty()) }}
        return (exact ?: plain ?: parts.firstOrNull())?.first?.code ?: lang
    }}
}}
"""


def swift_str(s):
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def build_swift():
    rows = ",\n".join(f'        Language(code: {swift_str(l["code"])}, name: {swift_str(l["name"])}, rtl: {str(l["rtl"]).lower()}, tag: {swift_str(l["tag"])}, lproj: {swift_str(l["ios"])})'
                      for l in LANGUAGES)
    return f"""// Generated by tools/gen_strings.py from shared/i18n/languages.json. Do not edit.
import Foundation

/// Interface languages: the app's own code (content packs, Ask), the name in itself, right-to-left, the
/// locale tag and the .lproj folder.
public enum Languages {{
    public struct Language: Sendable, Hashable {{
        public let code: String
        public let name: String
        public let rtl: Bool
        public let tag: String
        public let lproj: String
    }}

    public static let all: [Language] = [
{rows},
    ]
    private static let byCode = Dictionary(uniqueKeysWithValues: all.map {{ ($0.code, $0) }})

    public static func isRTL(_ code: String) -> Bool {{ byCode[code]?.rtl ?? false }}
    public static func tag(_ code: String) -> String {{ byCode[code]?.tag ?? code }}
    public static func lproj(_ code: String) -> String {{ byCode[code]?.lproj ?? code }}
    public static func name(_ code: String) -> String {{ byCode[code]?.name ?? code }}

    /// The app's code for a locale identifier ("fa-AF", "zh-Hans-CN", "fil", "in"), or nil when not offered.
    public static func code(identifier: String) -> String? {{
        let p = identifier.replacingOccurrences(of: "_", with: "-").split(separator: "-").map(String.init)
        guard var lang = p.first else {{ return nil }}
        if lang == "in" {{ lang = "id" }}
        if lang == "tl" {{ lang = "fil" }}
        let rest = Set(p.dropFirst())
        let same = all.filter {{ $0.tag.split(separator: "-").first.map(String.init) == lang }}
        if let exact = same.first(where: {{ l in l.tag.split(separator: "-").dropFirst().contains {{ rest.contains(String($0)) }} }}) {{ return exact.code }}
        let plain = same.first {{ l in
            let tail = l.tag.split(separator: "-").dropFirst()
            return tail.isEmpty || (tail.first?.count == 4 && !rest.contains {{ $0.count == 4 }})
        }}
        return (plain ?? same.first)?.code
    }}
}}
"""


def patch_project_yml():
    text = open(PROJECT_YML, encoding="utf-8").read()
    line = "CFBundleLocalizations: [" + ", ".join(l["ios"] for l in LANGUAGES) + "]"
    return re.sub(r"CFBundleLocalizations: \[[^\]]*\]", line, text)


def patch_gradle():
    """The APK keeps only the shipped languages' resources (localeFilters, from the res folder qualifiers)."""
    text = open(GRADLE, encoding="utf-8").read()
    quals = ["en"] + [l["android"][len("values-"):] for l in LANGUAGES if l["android"] != "values"]
    line = "localeFilters += listOf(" + ", ".join(f'"{q}"' for q in quals) + ")"
    return re.sub(r"localeFilters \+= listOf\([^)]*\)", line, text)


def main():
    check = "--check" in sys.argv
    data = json.load(open(SRC, encoding="utf-8"))
    data["languages"] = [l["code"] for l in LANGUAGES]
    errors = validate(data)
    if errors:
        print("\n".join(errors))
        sys.exit(1)
    outputs = {IOS_OUT: build_ios(data), IOS_OUT.replace("Localizable.xcstrings", "InfoPlist.xcstrings"): build_ios_infoplist(data),
               IOS_TV_INFOPLIST: build_ios_infoplist(data, tv=True)}
    for lang, d in ANDROID_DIR.items():
        outputs[os.path.join(ANDROID_RES, d, "strings.xml")] = build_android(data, lang)
    outputs[LOCALES_OUT] = build_locales_config()
    outputs[KOTLIN_OUT] = build_kotlin()
    outputs[SWIFT_OUT] = build_swift()
    outputs[PROJECT_YML] = patch_project_yml()
    outputs[GRADLE] = patch_gradle()
    stale = []
    for path, content in outputs.items():
        if check:
            if not os.path.exists(path) or open(path, encoding="utf-8").read() != content:
                stale.append(path)
        else:
            os.makedirs(os.path.dirname(path), exist_ok=True)
            with open(path, "w", encoding="utf-8") as f:
                f.write(content)
    if stale:
        print("out of date:", *stale, sep="\n  ")
        sys.exit(1)
    print(f"{len(data['strings'])} keys x {len(data['languages'])} languages " + ("ok" if check else "written"))


if __name__ == "__main__":
    main()
